apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJWbVZ5YjI1cGEyRlRhR1YyWTJoMWF6cG5hSEJmTXpWdWFHTXhTMHc0VDJWelJUVjBjRk5yWmpGNWJYSkhaWGRITm1Rek5EUXdia3RYIgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
